### ISSUE TITLE
Error box when starting program

### ISSUE THREAD

**Issue by hatanasinclaire** [cutie-lyta/MonikAI#1]
When starting up the program from the 0.11-pre release .exe it gives me these error boxes:
![image](https://user-images.githubusercontent.com/96905447/154023389-5af5aa78-5800-49d3-b1cb-380b68f0de3d.png)
![image](https://user-images.githubusercontent.com/96905447/154023460-ac15e39a-530b-4072-92c2-a931d2998c68.png)

This seems to be caused by [this line](https://github.com/cutie-lyta/MonikAI/blob/2257a5093e9d25e947e83b8812b2761b6f3b9616/MonikAI/Updater.cs#L69) in `Updater.cs` pointing to a dead link - I assume you must have changed your GitHub username or something. The `update.json` [in this repository](https://github.com/cutie-lyta/MonikAI/blob/main/docs/update.json) also seems to be full of dead links.

**Comment by s4pph1r3-dev** [comment]
That's the problem, yea, I forgot to update it when I changed my name and everything, I'm going to fix this right now

**Comment by s4pph1r3-dev** [comment]
I think it's fixed, now !
